### PR TITLE
Magnetohydrostatic Background Generation

### PR DESCRIPTION
**Pull request by fredgent**
All models for spruit, mfe_setup, paper1 and paper2 are now coded and ready for evaluation. For this plotting will be required. loops and hmi models need still to be coded

### CODE REVIEW

**Comment by fredgent** [comment]
astropy distribution has no u.one attribute, replaced with u.Unit(1)
units in tables are not attributed to elements in columns so multiplied by *.unit to solve

**Comment by Cadair** [comment]
@fredgent Wasn't `u.one` working on your Mac though? What version of astropy were you running when you had that issue? Run: `import astropy; print(astropy.__version__)`

**Comment by Cadair** [comment]
The better way to fix the elements of columns thing is to do a `u.Quantity(table['column'])` before you use it.

**Comment by fredgent** [comment]
Yes it was working on the Mac. I wanted to work on this today on my 
laptop and spent most of the afternoon instead debugging it.

I looked up the documentation on line for astropy and couldn't find any 
mention of u.one, but had the options for dimensionless units as 
u.Unit[''] or u.Unit[1] or any u.cm/u.cm works.

I have astropy 0.3.2

I'm also confused why on my laptop u.Quantity(table['T]) no longer 
converted the column into a temperature, when it worked fine on the Mac.
I used import pdb; pdb.set_trace() and  u.Quantity just gave an array of 
numbers, even though table['T'].unit was 'K'
using u.Quantity(table['T'])*table['T'].unit fixed this.

Fred

**Comment by fredgent** [comment]
The version of astropy on the Mac is 0.4

**Comment by fredgent** [comment]
ok I now have 0.4.2 I'll revert back to yesterday's pysac version

I didn't know how to check the version. Now I do.

Thanks

Fred

**Comment by fredgent** [comment]
This is completely fucked up.

How the hell do I revert to an earlier version?

I've spent three hours trying to revert to the state it was in twenty 
four hours ago and wish I had just edited the file manually (which took 
about 5 minutes), because now my repository is completely screwed. I 
have the version from Saturday on my Mac, but have no idea what state 
any of the remote branches are in and the repository on my laptop is 
stuck in the middle of an abortive merge, after following the on line 
instructions.

Fred

**Comment by Cadair** [comment]
Oh dear! I will pop in at some point today and see if I can recover it for you, and teach you some git foo at the same time.

**Comment by fredgent** [comment]
Thanks Stuart. After a detour to the car dealership I am now in work.

**Comment by Cadair** [comment]
So, now this is back to normal, what else is there todo?

**Comment by fredgent** [comment]
I am currently adding the necessary call in flux_tubes.py to produce the 
atmospheres for the multiple flux tube and loop configurations.

We also need to be able to reproduce the plots that were used in papers 
1 and 2 as well as any new plotting that may be useful.

I shall also add a new function to construct an HMI image and set of 
footpoint Bz from which to generate xi, yi, Si. I already have this in 
my original script, but need to consider how and where to include it in 
pysac.

For the loops I need still to explore suitable parameters, over which to 
construct the HMI atmosphere effectively, and for this I will need the 
plotting tools to view the results.

Fred

**Pull request closed without merging**
